image: golang:latest

stages:
  - test
  - build

format:
  stage: test
  script:
    - go fmt $(go list ./...)
    - go vet $(go list ./...)
    # - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - mkdir -p auth_service
    - go build -o auth_service ./...
  artifacts:
    paths:
      - auth_service
