# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bookings.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62ookings.proto\"y\n\x07\x42ooking\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\nlisting_id\x18\x02 \x01(\x05\x12\x0f\n\x07host_id\x18\x03 \x01(\x05\x12\x12\n\nstart_date\x18\x04 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x05 \x01(\t\x12\x12\n\npayment_id\x18\x06 \x01(\x05\")\n\x0c\x42ookingArray\x12\x19\n\x07\x62ooking\x18\x01 \x03(\x0b\x32\x08.Booking\" \n\rBookingUserId\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\" \n\rReturnMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2l\n\x0e\x42ookingService\x12\x33\n\x10GetBookingByUser\x12\x0e.BookingUserId\x1a\r.BookingArray\"\x00\x12%\n\rCreateBooking\x12\x08.Booking\x1a\x08.Booking\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bookings_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOKING._serialized_start=18
  _BOOKING._serialized_end=139
  _BOOKINGARRAY._serialized_start=141
  _BOOKINGARRAY._serialized_end=182
  _BOOKINGUSERID._serialized_start=184
  _BOOKINGUSERID._serialized_end=216
  _RETURNMESSAGE._serialized_start=218
  _RETURNMESSAGE._serialized_end=250
  _BOOKINGSERVICE._serialized_start=252
  _BOOKINGSERVICE._serialized_end=360
# @@protoc_insertion_point(module_scope)
