# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bookings.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62ookings.proto\"k\n\x07\x42ooking\x12\x0e\n\x06userId\x18\x01 \x01(\x05\x12\x11\n\tlistingId\x18\x02 \x01(\x05\x12\x0e\n\x06hostId\x18\x03 \x01(\x05\x12\r\n\x05start\x18\x04 \x01(\t\x12\x0b\n\x03\x65nd\x18\x05 \x01(\t\x12\x11\n\tpaymentId\x18\x06 \x01(\x05\"\x1f\n\rBookingUserId\x12\x0e\n\x06userId\x18\x01 \x01(\x05\" \n\rReturnMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2m\n\x0e\x42ookingService\x12.\n\x10GetBookingByUser\x12\x0e.BookingUserId\x1a\x08.Booking\"\x00\x12+\n\rCreateBooking\x12\x08.Booking\x1a\x0e.ReturnMessage\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bookings_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOKING._serialized_start=18
  _BOOKING._serialized_end=125
  _BOOKINGUSERID._serialized_start=127
  _BOOKINGUSERID._serialized_end=158
  _RETURNMESSAGE._serialized_start=160
  _RETURNMESSAGE._serialized_end=192
  _BOOKINGSERVICE._serialized_start=194
  _BOOKINGSERVICE._serialized_end=303
# @@protoc_insertion_point(module_scope)
