version: "3.8"

services:
  ui-test:
      build:
        context: ./
        dockerfile: Dockerfile
  
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    restart: always
    environment:
      - NODE_MAX_SESSION=5
    
