version: "3.1"
services:
  postgres:
    image: postgres:14.5
    networks:
      default:
        aliases:
          - postgres.app.site
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4:6
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@cs302.com
      PGADMIN_DEFAULT_PASSWORD: cs302_password
    ports:
      - "5431:80"
  
  bookings-service:
    image: bookings
    depends_on:
      - postgres
    environment:
      # must bind to [::] for port forwarding to work properly
      - HOST=[::]
      - PORT=50051
      - DB_USER=test_user
      - DB_PASS=test123
      - DB_HOST=postgres.app.site
      - DB_PORT=5432
      - DB_SCHEMA=localhost_bookings
    networks:
      default:
        aliases:
          - bookings_service
    ports:
      - "50051:50051"