import {
  StarIcon,
  PlusSquareIcon,
  ExternalLinkIcon,
  ChevronLeftIcon,
} from "@chakra-ui/icons";
import {
  Avatar,
  Box,
  Button,
  Container,
  Divider,
  Flex,
  FormLabel,
  Grid,
  GridItem,
  Heading,
  HStack,
  IconButton,
  Input,
  Modal,
  ModalBody,
  ModalCloseButton,
  ModalContent,
  ModalFooter,
  ModalHeader,
  ModalOverlay,
  SimpleGrid,
  Spacer,
  Text,
  useDisclosure,
  VStack,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Card } from "../../components/Card";
import Footer from "../../components/Footer";
import { Navbar } from "../../components/Navbar";
import Types from "../../components/Types";
import { DateRangePicker, Range, RangeKeyDict } from "react-date-range";
import "react-date-range/dist/styles.css";
import "react-date-range/dist/theme/default.css";
import { useState } from "react";
import { IoIosBed, IoIosPeople } from "react-icons/io";
import { MdMeetingRoom } from "react-icons/md";
import { BiBath } from "react-icons/bi";

const Listing: NextPage = () => {
  const { isOpen, onOpen, onClose } = useDisclosure();

  const [state, setState] = useState<Range[]>([
    {
      startDate: new Date(),
      endDate: new Date(),
      key: "selection",
    },
  ]);

  return (
    <div>
      <Head>
        <title>Localhost - Rent safely</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar main simple />

      <main>
        <Container maxW="container.xl" px={8} pt={5}>
          <Grid templateColumns="repeat(6, 1fr)" gap={1} mt={10} mb={80}>
            <GridItem colSpan={3} h="10" mr={8}>
              <HStack>
                <IconButton
                  aria-label="Search database"
                  icon={<ChevronLeftIcon />}
                  variant="ghost"
                  borderRadius="full"
                  ml="-3"
                />
                <Heading fontWeight="semibold" ml="2" letterSpacing="tight">
                  Confirm and pay
                </Heading>
              </HStack>
              <Box
                mt={12}
                border="1px"
                borderColor="gray.200"
                borderRadius="xl"
                px={5}
                py={5}
                maxW="450"
              >
                <Flex px={2}>
                  <Box>
                    <Text fontWeight="semibold" fontSize="sm">
                      This is a rare find.
                    </Text>
                    <Text>
                      Wayan&apos;s place on Airbnb is usually fully booked.
                    </Text>
                  </Box>
                  <Spacer />
                  <svg
                    viewBox="0 0 48 48"
                    xmlns="http://www.w3.org/2000/svg"
                    aria-hidden="true"
                    role="presentation"
                    focusable="false"
                    style={{
                      marginLeft: "15px",
                      display: "block",
                      height: "32px",
                      width: "32px",
                      fill: "rgb(227, 28, 95)",
                      stroke: "currentcolor",
                    }}
                  >
                    <g stroke="none">
                      <path
                        d="m32.62 6 9.526 11.114-18.146 23.921-18.147-23.921 9.526-11.114z"
                        fill-opacity=".2"
                      ></path>
                      <path d="m34.4599349 2 12.8243129 14.9616983-23.2842478 30.6928721-23.28424779-30.6928721 12.82431289-14.9616983zm-17.9171827 16h-12.52799999l18.25899999 24.069zm27.441 0h-12.528l-5.73 24.069zm-14.583 0h-10.802l5.4012478 22.684zm-15.92-12.86-9.30799999 10.86h11.89399999zm19.253-1.141h-17.468l2.857 12.001h11.754zm1.784 1.141-2.586 10.86h11.894z"></path>
                    </g>
                  </svg>
                </Flex>
              </Box>

              <Heading
                size="lg"
                fontWeight="semibold"
                mt={7}
                letterSpacing="tight"
              >
                Your trip
              </Heading>
              <Flex mt={7}>
                <Box>
                  <Text fontWeight="semibold">Dates</Text>
                  <Text>1 - 17 Oct 2023</Text>
                </Box>
                <Spacer />
                <Box>
                  <Text fontWeight="semibold">Edit</Text>
                </Box>
              </Flex>
              <Flex mt={7}>
                <Box>
                  <Text fontWeight="semibold">Guests</Text>
                  <Text>1 guest</Text>
                </Box>
                <Spacer />
                <Box>
                  <Text fontWeight="semibold">Edit</Text>
                </Box>
              </Flex>
              <Divider my={10} />
              <Heading
                size="lg"
                fontWeight="semibold"
                mt={7}
                letterSpacing="tight"
              >
                Choose how to pay
              </Heading>
            </GridItem>
            <GridItem colStart={4} colEnd={7} h="10" mb={80}>
              <Box
                border="1px"
                borderColor="gray.200"
                borderRadius="xl"
                width="400"
                height="fit-content"
                p={8}
              >
                <HStack>
                  <Image
                    src="https://a0.muscache.com/im/pictures/miso/Hosting-47721565/original/1854bf1b-dc40-49ed-9c2e-d378663a7a02.jpeg?im_w=720"
                    alt="Hello world"
                    objectFit="cover"
                    width={150}
                    height={120}
                    style={{ borderRadius: "10px" }}
                  />
                  <Box maxW="60%" pl={2}>
                    <Flex flexDirection="column">
                      <Text fontWeight="light" fontSize="xs">
                        Entire Villa
                      </Text>
                      <Text
                        fontWeight="normal"
                        fontSize="md"
                        lineHeight={0.9}
                        letterSpacing="tight"
                      >
                        Aura House 2bds Eco Bamboo House, Pool, River View
                      </Text>
                      <Spacer my={2} />
                      <HStack>
                        <StarIcon color="black.500" boxSize={3} />
                        <Text fontSize="sm">4.88 ·</Text>
                        <Text fontSize="sm">155 reviews ·</Text>
                      </HStack>
                    </Flex>
                  </Box>
                </HStack>
                <Divider my={6} />
                <Text letterSpacing="tight" fontSize="lg">
                  Your booking is protected by &nbsp;
                  <Image
                    src="https://a0.muscache.com/pictures/aircover/aircover-logo/original/56683a2f-f11b-43f6-8af7-a1b3861b2c85.svg"
                    width={60}
                    height={15}
                  />
                </Text>
                <Divider my={6} />
                <Heading
                  size="md"
                  fontWeight="semibold"
                  mt={7}
                  letterSpacing="tight"
                >
                  Price Details
                </Heading>
                <Flex mt={5}>
                  <Text fontSize="md" letterSpacing="tight">
                    $506.70 SGD x 7 nights
                  </Text>
                  <Spacer />
                  <Text fontSize="md" letterSpacing="tight">
                    $3,551.00 SGD
                  </Text>
                </Flex>
                <Flex mt={2}>
                  <Text fontSize="md" letterSpacing="tight">
                    Service fee
                  </Text>
                  <Spacer />
                  <Text fontSize="md" letterSpacing="tight">
                    $0.00 SGD
                  </Text>
                </Flex>
                <Divider py={2} />
                <Flex mt={5}>
                  <Text
                    fontSize="md"
                    letterSpacing="tight"
                    fontWeight="semibold"
                  >
                    Total (SGD)
                  </Text>
                  <Spacer />
                  <Text fontSize="md" letterSpacing="normal" fontWeight="bold">
                    $3,551.00
                  </Text>
                </Flex>
              </Box>
            </GridItem>
          </Grid>
        </Container>
      </main>
      <Footer />

      <Modal isOpen={isOpen} onClose={onClose} size="xl">
        <ModalOverlay />
        <ModalContent p={5}>
          <DateRangePicker
            editableDateInputs={true}
            onChange={(item) => setState([item.selection])}
            moveRangeOnFirstSelection={false}
            ranges={state}
          />
          <Button onClick={onClose}>Close</Button>
        </ModalContent>
      </Modal>
    </div>
  );
};

export default Listing;
