version: "3.1"

services:
  postgres:
    image: postgres:14.5
    networks:
      default:
        aliases:
          - postgres_db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: localhost_listings
    ports:
      - "5432:5432"

  listing_service:
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      default:
        aliases:
          - listing_service
    environment:
      PORT: 0.0.0.0:50051
      DB_USER: test_user
      DB_PASSWORD: test123
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_SCHEMA: localhost_listings
      AWS_BUCKET_NAME: cs302-localhost
      AWS_ACCESS_KEY_ID: AKIAZGIXCV3C7HWTXZ44
      AWS_SECRET_ACCESS_KEY: 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
    ports:
      - "50051:50051"

  listings_test:
    build:
      context: ../
      dockerfile: ci/Dockerfile
    depends_on:
      - listing_service
    environment:
      DB_CONN: postgres://test_user:test123@postgres_db:5432/localhost_listings
      LISTING_SVC: listing_service:50051
