# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health/health.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13health/health.proto\x12\x06health\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\x8c\x01\n\x13HealthCheckResponse\x12\x39\n\x06status\x18\x01 \x01(\x0e\x32).health.HealthCheckResponse.ServingStatus\":\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x32J\n\x06Health\x12@\n\x05\x43heck\x12\x1a.health.HealthCheckRequest\x1a\x1b.health.HealthCheckResponseB\x10Z\x0e./health.protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health.health_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\016./health.proto'
  _HEALTHCHECKREQUEST._serialized_start=31
  _HEALTHCHECKREQUEST._serialized_end=68
  _HEALTHCHECKRESPONSE._serialized_start=71
  _HEALTHCHECKRESPONSE._serialized_end=211
  _HEALTHCHECKRESPONSE_SERVINGSTATUS._serialized_start=153
  _HEALTHCHECKRESPONSE_SERVINGSTATUS._serialized_end=211
  _HEALTH._serialized_start=213
  _HEALTH._serialized_end=287
# @@protoc_insertion_point(module_scope)
