"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
_sym_db = _symbol_database.Default()
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
DESCRIPTOR = _descriptor.FileDescriptor(name='bookings.proto', package='bookings', syntax='proto3', serialized_options=None, serialized_pb=_b('\n\x0ebookings.proto\x12\x08bookings\x1a\x1fgoogle/protobuf/timestamp.proto"\x85\x01\n\x07Booking\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x12\n\nlisting_id\x18\x03 \x01(\x05\x12\x0f\n\x07host_id\x18\x04 \x01(\x05\x12\x12\n\nstart_date\x18\x05 \x01(\t\x12\x10\n\x08end_date\x18\x06 \x01(\t\x12\x12\n\npayment_id\x18\x07 \x01(\x05"\x90\x01\n\x1bGetAvailableListingsRequest\x12\x13\n\x0blisting_ids\x18\x01 \x03(\x05\x12.\n\nstart_date\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12,\n\x08end_date\x18\x03 \x01(\x0b2\x1a.google.protobuf.Timestamp"3\n\x1cGetAvailableListingsResponse\x12\x13\n\x0blisting_ids\x18\x01 \x03(\t"\x86\x01\n\x14CreateBookingRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\nlisting_id\x18\x02 \x01(\x05\x12\x0f\n\x07host_id\x18\x03 \x01(\x05\x12\x12\n\nstart_date\x18\x04 \x01(\t\x12\x10\n\x08end_date\x18\x05 \x01(\t\x12\x12\n\npayment_id\x18\x06 \x01(\x05">\n\x17GetBookingArrayResponse\x12#\n\x08bookings\x18\x01 \x03(\x0b2\x11.bookings.Booking"-\n\x17BookingByListingRequest\x12\x12\n\nlisting_id\x18\x01 \x01(\x05"\'\n\x14BookingByUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05"\x92\x01\n\x14UpdateBookingRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x12\n\nlisting_id\x18\x03 \x01(\x05\x12\x0f\n\x07host_id\x18\x04 \x01(\x05\x12\x12\n\nstart_date\x18\x05 \x01(\t\x12\x10\n\x08end_date\x18\x06 \x01(\t\x12\x12\n\npayment_id\x18\x07 \x01(\x05"\'\n\rReturnMessage\x12\x16\n\x0ereturn_message\x18\x01 \x01(\t2õ\x04\n\x0eBookingService\x12D\n\rCreateBooking\x12\x1e.bookings.CreateBookingRequest\x1a\x11.bookings.Booking"\x00\x12W\n\x10GetBookingByUser\x12\x1e.bookings.BookingByUserRequest\x1a!.bookings.GetBookingArrayResponse"\x00\x12]\n\x13GetBookingByListing\x12!.bookings.BookingByListingRequest\x1a!.bookings.GetBookingArrayResponse"\x00\x12N\n\x11UpdateBookingById\x12\x1e.bookings.UpdateBookingRequest\x1a\x17.bookings.ReturnMessage"\x00\x12R\n\x15DeleteBookingByUserId\x12\x1e.bookings.BookingByUserRequest\x1a\x17.bookings.ReturnMessage"\x00\x12X\n\x18DeleteBookingByListingId\x12!.bookings.BookingByListingRequest\x1a\x17.bookings.ReturnMessage"\x00\x12g\n\x14GetAvailableListings\x12%.bookings.GetAvailableListingsRequest\x1a&.bookings.GetAvailableListingsResponse"\x00b\x06proto3'), dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR])
_BOOKING = _descriptor.Descriptor(name='Booking', full_name='bookings.Booking', filename=None, file=DESCRIPTOR, containing_type=None, fields=[_descriptor.FieldDescriptor(name='id', full_name='bookings.Booking.id', index=0, number=1, type=5, cpp_type=1, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR), _descriptor.FieldDescriptor(name='user_id', full_name='bookings.Booking.user_id', index=1, number=2, type=5, cpp_type=1, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR), _descriptor.FieldDescriptor(name='listing_id', full_name='bookings.Booking.listing_id', index=2, number=3, type=5, cpp_type=1, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR), _descriptor.FieldDescriptor(name='host_id', full_name='bookings.Booking.host_id', index=3, number=4, type=5, cpp_type=1, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR), _descriptor.FieldDescriptor(name='start_date', full_name='bookings.Booking.start_date', index=4, number=5, type=9, cpp_type=9, label=1, has_default_value=False, default_value=_b('').decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR), _descriptor.FieldDescriptor(name='end_date', full_name='bookings.Booking.end_date', index=5, number=6, type=9, cpp_type=9, label=1, has_default_value=False, default_value=_b('').decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR), _descriptor.FieldDescriptor(name='payment_id', full_name='bookings.Booking.payment_id', index=6, number=7, type=5, cpp_type=1, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=62, serialized_end=195)
_GETAVAILABLELISTINGSREQUEST = _descriptor.Descriptor(name='GetAvailableListingsRequest', full_name='bookings.GetAvailableListingsRequest', filename=None, file=DESCRIPTOR, containing_type=None, fields=[_descriptor.FieldDescriptor(name='listing_ids', full_name='bookings.GetAvailableListingsRequest.listing_ids', index=0, number=1, type=5, cpp_type=1, label=3, has_default_value=False, default_value=[], message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR), _descriptor.FieldDescriptor(name='start_date', full_name='bookings.GetAvailableListingsRequest.start_date', index=1, number=2, type=11, cpp_type=10, label=1, has_default_value=False, default_value=None, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR), _descriptor.FieldDescriptor(name='end_date', full_name='bookings.GetAvailableListingsRequest.end_date', index=2, number=3, type=11, cpp_type=10, label=1, has_default_value=False, default_value=None, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=198, serialized_end=342)
_GETAVAILABLELISTINGSRESPONSE = _descriptor.Descriptor(name='GetAvailableListingsResponse', full_name='bookings.GetAvailableListingsResponse', filename=None, file=DESCRIPTOR, containing_type=None, fields=[_descriptor.FieldDescriptor(name='listing_ids', full_name='bookings.GetAvailableListingsResponse.listing_ids', index=0, number=1, type=9, cpp_type=9, label=3, has_default_value=False, default_value=[], message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=344, serialized_end=395)
_CREATEBOOKINGREQUEST = _descriptor.Descriptor(name='CreateBookingRequest', full_name='bookings.CreateBookingRequest', filename=None, file=DESCRIPTOR, containing_type=None, fields=[_descriptor.FieldDescriptor(name='user_id', full_name='bookings.CreateBookingRequest.user_id', index=0, number=1, type=5, cpp_type=1, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR), _descriptor.FieldDescriptor(name='listing_id', full_name='bookings.CreateBookingRequest.listing_id', index=1, number=2, type=5, cpp_type=1, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR), _descriptor.FieldDescriptor(name='host_id', full_name='bookings.CreateBookingRequest.host_id', index=2, number=3, type=5, cpp_type=1, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR), _descriptor.FieldDescriptor(name='start_date', full_name='bookings.CreateBookingRequest.start_date', index=3, number=4, type=9, cpp_type=9, label=1, has_default_value=False, default_value=_b('').decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR), _descriptor.FieldDescriptor(name='end_date', full_name='bookings.CreateBookingRequest.end_date', index=4, number=5, type=9, cpp_type=9, label=1, has_default_value=False, default_value=_b('').decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR), _descriptor.FieldDescriptor(name='payment_id', full_name='bookings.CreateBookingRequest.payment_id', index=5, number=6, type=5, cpp_type=1, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=398, serialized_end=532)
_GETBOOKINGARRAYRESPONSE = _descriptor.Descriptor(name='GetBookingArrayResponse', full_name='bookings.GetBookingArrayResponse', filename=None, file=DESCRIPTOR, containing_type=None, fields=[_descriptor.FieldDescriptor(name='bookings', full_name='bookings.GetBookingArrayResponse.bookings', index=0, number=1, type=11, cpp_type=10, label=3, has_default_value=False, default_value=[], message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=534, serialized_end=596)
_BOOKINGBYLISTINGREQUEST = _descriptor.Descriptor(name='BookingByListingRequest', full_name='bookings.BookingByListingRequest', filename=None, file=DESCRIPTOR, containing_type=None, fields=[_descriptor.FieldDescriptor(name='listing_id', full_name='bookings.BookingByListingRequest.listing_id', index=0, number=1, type=5, cpp_type=1, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=598, serialized_end=643)
_BOOKINGBYUSERREQUEST = _descriptor.Descriptor(name='BookingByUserRequest', full_name='bookings.BookingByUserRequest', filename=None, file=DESCRIPTOR, containing_type=None, fields=[_descriptor.FieldDescriptor(name='user_id', full_name='bookings.BookingByUserRequest.user_id', index=0, number=1, type=5, cpp_type=1, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=645, serialized_end=684)
_UPDATEBOOKINGREQUEST = _descriptor.Descriptor(name='UpdateBookingRequest', full_name='bookings.UpdateBookingRequest', filename=None, file=DESCRIPTOR, containing_type=None, fields=[_descriptor.FieldDescriptor(name='id', full_name='bookings.UpdateBookingRequest.id', index=0, number=1, type=5, cpp_type=1, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR), _descriptor.FieldDescriptor(name='user_id', full_name='bookings.UpdateBookingRequest.user_id', index=1, number=2, type=5, cpp_type=1, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR), _descriptor.FieldDescriptor(name='listing_id', full_name='bookings.UpdateBookingRequest.listing_id', index=2, number=3, type=5, cpp_type=1, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR), _descriptor.FieldDescriptor(name='host_id', full_name='bookings.UpdateBookingRequest.host_id', index=3, number=4, type=5, cpp_type=1, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR), _descriptor.FieldDescriptor(name='start_date', full_name='bookings.UpdateBookingRequest.start_date', index=4, number=5, type=9, cpp_type=9, label=1, has_default_value=False, default_value=_b('').decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR), _descriptor.FieldDescriptor(name='end_date', full_name='bookings.UpdateBookingRequest.end_date', index=5, number=6, type=9, cpp_type=9, label=1, has_default_value=False, default_value=_b('').decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR), _descriptor.FieldDescriptor(name='payment_id', full_name='bookings.UpdateBookingRequest.payment_id', index=6, number=7, type=5, cpp_type=1, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=687, serialized_end=833)
_RETURNMESSAGE = _descriptor.Descriptor(name='ReturnMessage', full_name='bookings.ReturnMessage', filename=None, file=DESCRIPTOR, containing_type=None, fields=[_descriptor.FieldDescriptor(name='return_message', full_name='bookings.ReturnMessage.return_message', index=0, number=1, type=9, cpp_type=9, label=1, has_default_value=False, default_value=_b('').decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=835, serialized_end=874)
_GETAVAILABLELISTINGSREQUEST.fields_by_name['start_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETAVAILABLELISTINGSREQUEST.fields_by_name['end_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GETBOOKINGARRAYRESPONSE.fields_by_name['bookings'].message_type = _BOOKING
DESCRIPTOR.message_types_by_name['Booking'] = _BOOKING
DESCRIPTOR.message_types_by_name['GetAvailableListingsRequest'] = _GETAVAILABLELISTINGSREQUEST
DESCRIPTOR.message_types_by_name['GetAvailableListingsResponse'] = _GETAVAILABLELISTINGSRESPONSE
DESCRIPTOR.message_types_by_name['CreateBookingRequest'] = _CREATEBOOKINGREQUEST
DESCRIPTOR.message_types_by_name['GetBookingArrayResponse'] = _GETBOOKINGARRAYRESPONSE
DESCRIPTOR.message_types_by_name['BookingByListingRequest'] = _BOOKINGBYLISTINGREQUEST
DESCRIPTOR.message_types_by_name['BookingByUserRequest'] = _BOOKINGBYUSERREQUEST
DESCRIPTOR.message_types_by_name['UpdateBookingRequest'] = _UPDATEBOOKINGREQUEST
DESCRIPTOR.message_types_by_name['ReturnMessage'] = _RETURNMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)
Booking = _reflection.GeneratedProtocolMessageType('Booking', (_message.Message,), dict(DESCRIPTOR=_BOOKING, __module__='bookings_pb2'))
_sym_db.RegisterMessage(Booking)
GetAvailableListingsRequest = _reflection.GeneratedProtocolMessageType('GetAvailableListingsRequest', (_message.Message,), dict(DESCRIPTOR=_GETAVAILABLELISTINGSREQUEST, __module__='bookings_pb2'))
_sym_db.RegisterMessage(GetAvailableListingsRequest)
GetAvailableListingsResponse = _reflection.GeneratedProtocolMessageType('GetAvailableListingsResponse', (_message.Message,), dict(DESCRIPTOR=_GETAVAILABLELISTINGSRESPONSE, __module__='bookings_pb2'))
_sym_db.RegisterMessage(GetAvailableListingsResponse)
CreateBookingRequest = _reflection.GeneratedProtocolMessageType('CreateBookingRequest', (_message.Message,), dict(DESCRIPTOR=_CREATEBOOKINGREQUEST, __module__='bookings_pb2'))
_sym_db.RegisterMessage(CreateBookingRequest)
GetBookingArrayResponse = _reflection.GeneratedProtocolMessageType('GetBookingArrayResponse', (_message.Message,), dict(DESCRIPTOR=_GETBOOKINGARRAYRESPONSE, __module__='bookings_pb2'))
_sym_db.RegisterMessage(GetBookingArrayResponse)
BookingByListingRequest = _reflection.GeneratedProtocolMessageType('BookingByListingRequest', (_message.Message,), dict(DESCRIPTOR=_BOOKINGBYLISTINGREQUEST, __module__='bookings_pb2'))
_sym_db.RegisterMessage(BookingByListingRequest)
BookingByUserRequest = _reflection.GeneratedProtocolMessageType('BookingByUserRequest', (_message.Message,), dict(DESCRIPTOR=_BOOKINGBYUSERREQUEST, __module__='bookings_pb2'))
_sym_db.RegisterMessage(BookingByUserRequest)
UpdateBookingRequest = _reflection.GeneratedProtocolMessageType('UpdateBookingRequest', (_message.Message,), dict(DESCRIPTOR=_UPDATEBOOKINGREQUEST, __module__='bookings_pb2'))
_sym_db.RegisterMessage(UpdateBookingRequest)
ReturnMessage = _reflection.GeneratedProtocolMessageType('ReturnMessage', (_message.Message,), dict(DESCRIPTOR=_RETURNMESSAGE, __module__='bookings_pb2'))
_sym_db.RegisterMessage(ReturnMessage)
_BOOKINGSERVICE = _descriptor.ServiceDescriptor(name='BookingService', full_name='bookings.BookingService', file=DESCRIPTOR, index=0, serialized_options=None, serialized_start=877, serialized_end=1506, methods=[_descriptor.MethodDescriptor(name='CreateBooking', full_name='bookings.BookingService.CreateBooking', index=0, containing_service=None, input_type=_CREATEBOOKINGREQUEST, output_type=_BOOKING, serialized_options=None), _descriptor.MethodDescriptor(name='GetBookingByUser', full_name='bookings.BookingService.GetBookingByUser', index=1, containing_service=None, input_type=_BOOKINGBYUSERREQUEST, output_type=_GETBOOKINGARRAYRESPONSE, serialized_options=None), _descriptor.MethodDescriptor(name='GetBookingByListing', full_name='bookings.BookingService.GetBookingByListing', index=2, containing_service=None, input_type=_BOOKINGBYLISTINGREQUEST, output_type=_GETBOOKINGARRAYRESPONSE, serialized_options=None), _descriptor.MethodDescriptor(name='UpdateBookingById', full_name='bookings.BookingService.UpdateBookingById', index=3, containing_service=None, input_type=_UPDATEBOOKINGREQUEST, output_type=_RETURNMESSAGE, serialized_options=None), _descriptor.MethodDescriptor(name='DeleteBookingByUserId', full_name='bookings.BookingService.DeleteBookingByUserId', index=4, containing_service=None, input_type=_BOOKINGBYUSERREQUEST, output_type=_RETURNMESSAGE, serialized_options=None), _descriptor.MethodDescriptor(name='DeleteBookingByListingId', full_name='bookings.BookingService.DeleteBookingByListingId', index=5, containing_service=None, input_type=_BOOKINGBYLISTINGREQUEST, output_type=_RETURNMESSAGE, serialized_options=None), _descriptor.MethodDescriptor(name='GetAvailableListings', full_name='bookings.BookingService.GetAvailableListings', index=6, containing_service=None, input_type=_GETAVAILABLELISTINGSREQUEST, output_type=_GETAVAILABLELISTINGSRESPONSE, serialized_options=None)])
_sym_db.RegisterServiceDescriptor(_BOOKINGSERVICE)
DESCRIPTOR.services_by_name['BookingService'] = _BOOKINGSERVICE
