# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bookings/bookings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bookings/bookings.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17\x62ookings/bookings.proto\"\x85\x01\n\x07\x42ooking\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x12\n\nlisting_id\x18\x03 \x01(\x05\x12\x0f\n\x07host_id\x18\x04 \x01(\x05\x12\x12\n\nstart_date\x18\x05 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x06 \x01(\t\x12\x12\n\npayment_id\x18\x07 \x01(\x05\"\x86\x01\n\x14\x43reateBookingRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\nlisting_id\x18\x02 \x01(\x05\x12\x0f\n\x07host_id\x18\x03 \x01(\x05\x12\x12\n\nstart_date\x18\x04 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x05 \x01(\t\x12\x12\n\npayment_id\x18\x06 \x01(\x05\"5\n\x17GetBookingArrayResponse\x12\x1a\n\x08\x62ookings\x18\x01 \x03(\x0b\x32\x08.Booking\"-\n\x17\x42ookingByListingRequest\x12\x12\n\nlisting_id\x18\x01 \x01(\x05\"\'\n\x14\x42ookingByUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\x92\x01\n\x14UpdateBookingRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x12\n\nlisting_id\x18\x03 \x01(\x05\x12\x0f\n\x07host_id\x18\x04 \x01(\x05\x12\x12\n\nstart_date\x18\x05 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x06 \x01(\t\x12\x12\n\npayment_id\x18\x07 \x01(\x05\"\'\n\rReturnMessage\x12\x16\n\x0ereturn_message\x18\x01 \x01(\t2\xa0\x03\n\x0e\x42ookingService\x12\x32\n\rCreateBooking\x12\x15.CreateBookingRequest\x1a\x08.Booking\"\x00\x12\x45\n\x10GetBookingByUser\x12\x15.BookingByUserRequest\x1a\x18.GetBookingArrayResponse\"\x00\x12K\n\x13GetBookingByListing\x12\x18.BookingByListingRequest\x1a\x18.GetBookingArrayResponse\"\x00\x12<\n\x11UpdateBookingById\x12\x15.UpdateBookingRequest\x1a\x0e.ReturnMessage\"\x00\x12@\n\x15\x44\x65leteBookingByUserId\x12\x15.BookingByUserRequest\x1a\x0e.ReturnMessage\"\x00\x12\x46\n\x18\x44\x65leteBookingByListingId\x12\x18.BookingByListingRequest\x1a\x0e.ReturnMessage\"\x00\x62\x06proto3')
)




_BOOKING = _descriptor.Descriptor(
  name='Booking',
  full_name='Booking',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Booking.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='Booking.user_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='listing_id', full_name='Booking.listing_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host_id', full_name='Booking.host_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_date', full_name='Booking.start_date', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_date', full_name='Booking.end_date', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payment_id', full_name='Booking.payment_id', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=161,
)


_CREATEBOOKINGREQUEST = _descriptor.Descriptor(
  name='CreateBookingRequest',
  full_name='CreateBookingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='CreateBookingRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='listing_id', full_name='CreateBookingRequest.listing_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host_id', full_name='CreateBookingRequest.host_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_date', full_name='CreateBookingRequest.start_date', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_date', full_name='CreateBookingRequest.end_date', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payment_id', full_name='CreateBookingRequest.payment_id', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=298,
)


_GETBOOKINGARRAYRESPONSE = _descriptor.Descriptor(
  name='GetBookingArrayResponse',
  full_name='GetBookingArrayResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bookings', full_name='GetBookingArrayResponse.bookings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=353,
)


_BOOKINGBYLISTINGREQUEST = _descriptor.Descriptor(
  name='BookingByListingRequest',
  full_name='BookingByListingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='listing_id', full_name='BookingByListingRequest.listing_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=400,
)


_BOOKINGBYUSERREQUEST = _descriptor.Descriptor(
  name='BookingByUserRequest',
  full_name='BookingByUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='BookingByUserRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=402,
  serialized_end=441,
)


_UPDATEBOOKINGREQUEST = _descriptor.Descriptor(
  name='UpdateBookingRequest',
  full_name='UpdateBookingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UpdateBookingRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='UpdateBookingRequest.user_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='listing_id', full_name='UpdateBookingRequest.listing_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host_id', full_name='UpdateBookingRequest.host_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_date', full_name='UpdateBookingRequest.start_date', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_date', full_name='UpdateBookingRequest.end_date', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payment_id', full_name='UpdateBookingRequest.payment_id', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=444,
  serialized_end=590,
)


_RETURNMESSAGE = _descriptor.Descriptor(
  name='ReturnMessage',
  full_name='ReturnMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='return_message', full_name='ReturnMessage.return_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=592,
  serialized_end=631,
)

_GETBOOKINGARRAYRESPONSE.fields_by_name['bookings'].message_type = _BOOKING
DESCRIPTOR.message_types_by_name['Booking'] = _BOOKING
DESCRIPTOR.message_types_by_name['CreateBookingRequest'] = _CREATEBOOKINGREQUEST
DESCRIPTOR.message_types_by_name['GetBookingArrayResponse'] = _GETBOOKINGARRAYRESPONSE
DESCRIPTOR.message_types_by_name['BookingByListingRequest'] = _BOOKINGBYLISTINGREQUEST
DESCRIPTOR.message_types_by_name['BookingByUserRequest'] = _BOOKINGBYUSERREQUEST
DESCRIPTOR.message_types_by_name['UpdateBookingRequest'] = _UPDATEBOOKINGREQUEST
DESCRIPTOR.message_types_by_name['ReturnMessage'] = _RETURNMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Booking = _reflection.GeneratedProtocolMessageType('Booking', (_message.Message,), dict(
  DESCRIPTOR = _BOOKING,
  __module__ = 'bookings.bookings_pb2'
  # @@protoc_insertion_point(class_scope:Booking)
  ))
_sym_db.RegisterMessage(Booking)

CreateBookingRequest = _reflection.GeneratedProtocolMessageType('CreateBookingRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEBOOKINGREQUEST,
  __module__ = 'bookings.bookings_pb2'
  # @@protoc_insertion_point(class_scope:CreateBookingRequest)
  ))
_sym_db.RegisterMessage(CreateBookingRequest)

GetBookingArrayResponse = _reflection.GeneratedProtocolMessageType('GetBookingArrayResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETBOOKINGARRAYRESPONSE,
  __module__ = 'bookings.bookings_pb2'
  # @@protoc_insertion_point(class_scope:GetBookingArrayResponse)
  ))
_sym_db.RegisterMessage(GetBookingArrayResponse)

BookingByListingRequest = _reflection.GeneratedProtocolMessageType('BookingByListingRequest', (_message.Message,), dict(
  DESCRIPTOR = _BOOKINGBYLISTINGREQUEST,
  __module__ = 'bookings.bookings_pb2'
  # @@protoc_insertion_point(class_scope:BookingByListingRequest)
  ))
_sym_db.RegisterMessage(BookingByListingRequest)

BookingByUserRequest = _reflection.GeneratedProtocolMessageType('BookingByUserRequest', (_message.Message,), dict(
  DESCRIPTOR = _BOOKINGBYUSERREQUEST,
  __module__ = 'bookings.bookings_pb2'
  # @@protoc_insertion_point(class_scope:BookingByUserRequest)
  ))
_sym_db.RegisterMessage(BookingByUserRequest)

UpdateBookingRequest = _reflection.GeneratedProtocolMessageType('UpdateBookingRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEBOOKINGREQUEST,
  __module__ = 'bookings.bookings_pb2'
  # @@protoc_insertion_point(class_scope:UpdateBookingRequest)
  ))
_sym_db.RegisterMessage(UpdateBookingRequest)

ReturnMessage = _reflection.GeneratedProtocolMessageType('ReturnMessage', (_message.Message,), dict(
  DESCRIPTOR = _RETURNMESSAGE,
  __module__ = 'bookings.bookings_pb2'
  # @@protoc_insertion_point(class_scope:ReturnMessage)
  ))
_sym_db.RegisterMessage(ReturnMessage)



_BOOKINGSERVICE = _descriptor.ServiceDescriptor(
  name='BookingService',
  full_name='BookingService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=634,
  serialized_end=1050,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateBooking',
    full_name='BookingService.CreateBooking',
    index=0,
    containing_service=None,
    input_type=_CREATEBOOKINGREQUEST,
    output_type=_BOOKING,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetBookingByUser',
    full_name='BookingService.GetBookingByUser',
    index=1,
    containing_service=None,
    input_type=_BOOKINGBYUSERREQUEST,
    output_type=_GETBOOKINGARRAYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetBookingByListing',
    full_name='BookingService.GetBookingByListing',
    index=2,
    containing_service=None,
    input_type=_BOOKINGBYLISTINGREQUEST,
    output_type=_GETBOOKINGARRAYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateBookingById',
    full_name='BookingService.UpdateBookingById',
    index=3,
    containing_service=None,
    input_type=_UPDATEBOOKINGREQUEST,
    output_type=_RETURNMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteBookingByUserId',
    full_name='BookingService.DeleteBookingByUserId',
    index=4,
    containing_service=None,
    input_type=_BOOKINGBYUSERREQUEST,
    output_type=_RETURNMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteBookingByListingId',
    full_name='BookingService.DeleteBookingByListingId',
    index=5,
    containing_service=None,
    input_type=_BOOKINGBYLISTINGREQUEST,
    output_type=_RETURNMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOOKINGSERVICE)

DESCRIPTOR.services_by_name['BookingService'] = _BOOKINGSERVICE

# @@protoc_insertion_point(module_scope)
