import { HStack } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Card } from "../components/Card";
import DarkModeToggle from "../components/DarkModeToggle";
import Footer from "../components/Footer";
import { Navbar } from "../components/Navbar";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={styles.main}>
        <HStack placeContent="center">
          <Card />
          <Card />
          <Card />
          <Card />
        </HStack>
        <HStack placeContent="center">
          <Card />
          <Card />
          <Card />
          <Card />
        </HStack>
      </main>
      <Footer />
    </div>
  );
};

export default Home;
