version: "3.1"

services:
  postgres:
    image: postgres:14.5
    networks:
      default:
        aliases:
          - postgres_db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: localhost_users
    ports:
      - "5432:5432"

  auth_service:
    image: auth_user
    depends_on:
      - postgres
    networks:
      default:
        aliases:
          - auth_service
    environment:
      PORT: 0.0.0.0:50051
      DB_USER: test_user
      DB_PASSWORD: test123
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_SCHEMA: localhost_users
      JWT_SECRET_KEY: test_secret
    ports:
      - "50051:50051"

  authentication_test:
    build:
      context: ../
      dockerfile: ci/Dockerfile
    depends_on:
      - auth_service
    environment:
      DB_CONN: postgres://test_user:test123@postgres_db:5432/localhost_users
      AUTH_SVC: auth_service:50051
