import { StarIcon, PlusSquareIcon, ExternalLinkIcon } from "@chakra-ui/icons";
import {
  Box,
  Button,
  Center,
  Container,
  Divider,
  Grid,
  GridItem,
  Heading,
  HStack,
  Text,
  useColorModeValue,
  VStack,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Footer from "../../components/Footer";
import "react-date-range/dist/styles.css";
import "react-date-range/dist/theme/default.css";
import Logo from "./../../public/localhost.png";
import Jye from "./../../public/Jye.jpg";
import Jianwei from "./../../public/Jianwei.jpg";
import Justin from "./../../public/Justin.jpg";
import Nich from "./../../public/Nich.jpg";
import Omer from "./../../public/Omer.jpg";
import LogoDark from "./../../public/localhost_dark.png";

const Failure: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Localhost - Rent safely</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center mt={10}>
        <Image
          src={useColorModeValue(Logo, LogoDark)}
          height="31px"
          width="156.75px"
        />
      </Center>

      <main>
        <Container maxW="container.2xl" px={8} pt={5}>
          <Center mt={10}>
            <VStack textAlign="center">
              <Heading fontWeight="bold" letterSpacing="tight" width="100%">
                Payment Failed
              </Heading>
              <Text fontSize="md" letterSpacing="tight">
                Uh-oh Booking request was not set due to an error - please try
                again.
              </Text>
            </VStack>
          </Center>

          <Center mt={10}>
            <VStack
              border="1px"
              borderColor="gray.200"
              height={300}
              p={7}
              boxShadow="md"
            >
              <Heading fontSize="xl" fontWeight="bold" color="red.500">
                This cannot be tolerated!{" "}
              </Heading>
              <Text fontSize="md" letterSpacing="tight">
                Someone from our team has to take responsibility. Pick someone
                to fire
              </Text>
              <Grid templateColumns="repeat(6, 1fr)" pt={6}>
                <GridItem colSpan={1} h="10">
                  <Container>
                    <VStack>
                      <Image
                        src={Nich}
                        height={100}
                        width={100}
                        style={{ borderRadius: "15px" }}
                      />
                      <Button colorScheme="red">Fire Nicholas</Button>
                    </VStack>
                  </Container>
                </GridItem>
                <GridItem colSpan={1} h="10">
                  <Container>
                    <VStack>
                      <Image
                        src={Omer}
                        height={100}
                        width={100}
                        style={{ borderRadius: "15px" }}
                      />
                      <Button colorScheme="red">Fire Omer</Button>
                    </VStack>
                  </Container>
                </GridItem>
                <GridItem colSpan={1} h="10">
                  <Container>
                    <VStack>
                      <Image
                        src={Jye}
                        height={100}
                        width={100}
                        style={{ borderRadius: "15px" }}
                      />
                      <Button colorScheme="red">Fire Jye Yi</Button>
                    </VStack>
                  </Container>
                </GridItem>
                <GridItem colSpan={1} h="10">
                  <Container>
                    <VStack>
                      <Image
                        src="https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/13086308_RXL1_20220207.jpg"
                        height={100}
                        width={100}
                      />
                      <Button colorScheme="red">Fire Jasmine</Button>
                    </VStack>
                  </Container>
                </GridItem>
                <GridItem colSpan={1} h="10">
                  <Container>
                    <VStack>
                      <Image
                        src={Justin}
                        height={100}
                        width={100}
                        style={{ borderRadius: "15px" }}
                      />
                      <Button colorScheme="red">Fire Justin</Button>
                    </VStack>
                  </Container>
                </GridItem>
                <GridItem colSpan={1} h="10">
                  <Container>
                    <VStack>
                      <Image
                        src={Jianwei}
                        height={100}
                        width={100}
                        style={{ borderRadius: "15px" }}
                      />
                      <Button colorScheme="red">Fire Jian Wei</Button>
                    </VStack>
                  </Container>
                </GridItem>
              </Grid>
            </VStack>
          </Center>
        </Container>
      </main>
      <Footer />
    </div>
  );
};

export default Failure;
