# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bookings/bookings.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x62ookings/bookings.proto\"\x85\x01\n\x07\x42ooking\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x12\n\nlisting_id\x18\x03 \x01(\x05\x12\x0f\n\x07host_id\x18\x04 \x01(\x05\x12\x12\n\nstart_date\x18\x05 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x06 \x01(\t\x12\x12\n\npayment_id\x18\x07 \x01(\x05\"\x86\x01\n\x14\x43reateBookingRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\nlisting_id\x18\x02 \x01(\x05\x12\x0f\n\x07host_id\x18\x03 \x01(\x05\x12\x12\n\nstart_date\x18\x04 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x05 \x01(\t\x12\x12\n\npayment_id\x18\x06 \x01(\x05\"5\n\x17GetBookingArrayResponse\x12\x1a\n\x08\x62ookings\x18\x01 \x03(\x0b\x32\x08.Booking\"-\n\x17\x42ookingByListingRequest\x12\x12\n\nlisting_id\x18\x01 \x01(\x05\"\'\n\x14\x42ookingByUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\x92\x01\n\x14UpdateBookingRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x12\n\nlisting_id\x18\x03 \x01(\x05\x12\x0f\n\x07host_id\x18\x04 \x01(\x05\x12\x12\n\nstart_date\x18\x05 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x06 \x01(\t\x12\x12\n\npayment_id\x18\x07 \x01(\x05\"\'\n\rReturnMessage\x12\x16\n\x0ereturn_message\x18\x01 \x01(\t2\xa0\x03\n\x0e\x42ookingService\x12\x32\n\rCreateBooking\x12\x15.CreateBookingRequest\x1a\x08.Booking\"\x00\x12\x45\n\x10GetBookingByUser\x12\x15.BookingByUserRequest\x1a\x18.GetBookingArrayResponse\"\x00\x12K\n\x13GetBookingByListing\x12\x18.BookingByListingRequest\x1a\x18.GetBookingArrayResponse\"\x00\x12<\n\x11UpdateBookingById\x12\x15.UpdateBookingRequest\x1a\x0e.ReturnMessage\"\x00\x12@\n\x15\x44\x65leteBookingByUserId\x12\x15.BookingByUserRequest\x1a\x0e.ReturnMessage\"\x00\x12\x46\n\x18\x44\x65leteBookingByListingId\x12\x18.BookingByListingRequest\x1a\x0e.ReturnMessage\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bookings.bookings_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOKING._serialized_start=28
  _BOOKING._serialized_end=161
  _CREATEBOOKINGREQUEST._serialized_start=164
  _CREATEBOOKINGREQUEST._serialized_end=298
  _GETBOOKINGARRAYRESPONSE._serialized_start=300
  _GETBOOKINGARRAYRESPONSE._serialized_end=353
  _BOOKINGBYLISTINGREQUEST._serialized_start=355
  _BOOKINGBYLISTINGREQUEST._serialized_end=400
  _BOOKINGBYUSERREQUEST._serialized_start=402
  _BOOKINGBYUSERREQUEST._serialized_end=441
  _UPDATEBOOKINGREQUEST._serialized_start=444
  _UPDATEBOOKINGREQUEST._serialized_end=590
  _RETURNMESSAGE._serialized_start=592
  _RETURNMESSAGE._serialized_end=631
  _BOOKINGSERVICE._serialized_start=634
  _BOOKINGSERVICE._serialized_end=1050
# @@protoc_insertion_point(module_scope)
